(()=>{
 if(document.getElementById('telegram-atendimento-inline'))return;
 const host=document.createElement('div');host.id='telegram-atendimento-inline';host.hidden=true;host.style.cssText='position:fixed;z-index:2147483646;box-sizing:border-box;';
 const root=host.attachShadow({mode:'closed'});root.innerHTML=`<style>*{box-sizing:border-box}.bar{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#fff;border:1px solid #dce7e2;border-radius:13px;padding:8px 10px;box-shadow:0 8px 28px #102b201f;display:flex;align-items:center;gap:9px;min-height:52px}.label{display:flex;align-items:center;gap:6px;flex:0 0 auto;color:#167c5c;font-size:11px;font-weight:750;padding-right:9px;border-right:1px solid #e5ece8}.mark{display:grid;place-items:center;width:28px;height:28px;border-radius:8px;background:#129b6a;color:#fff;font-size:17px}.list{display:flex;gap:7px;overflow-x:auto;scrollbar-width:thin;flex:1;padding:1px}.audio{display:flex;align-items:center;gap:7px;flex:0 0 auto;max-width:190px;border:1px solid #dce8e2;background:#f7faf8;color:#273b33;border-radius:9px;padding:8px 10px;cursor:pointer;font:600 12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;white-space:nowrap}.audio:hover{background:#eaf7f0;border-color:#9fd6bb}.audio:disabled{opacity:.55;cursor:wait}.audio span:last-child{overflow:hidden;text-overflow:ellipsis}.play{color:#109466;font-size:12px}.state{font-size:11px;color:#77877f;padding:0 8px;white-space:nowrap}.state.error{color:#a7523f}.refresh{flex:0 0 auto;border:0;background:#eef4f1;color:#5c7468;border-radius:8px;width:31px;height:31px;cursor:pointer;font-size:16px}</style><div class="bar"><div class="label"><span class="mark">♪</span><span>Áudios</span></div><div class="list"><span class="state">Carregando…</span></div><button class="refresh" title="Atualizar áudios">↻</button></div>`;
 const list=root.querySelector('.list'),refresh=root.querySelector('.refresh');let items=[],loading=false,lastLoad=0,sending=false;
 async function api(path,{method='GET',body}={}){const response=await chrome.runtime.sendMessage({type:'api',path,method,body});if(!response?.ok)throw new Error(response?.error||'A extensão não respondeu.');return response.data;}
 function state(text,error=false){list.replaceChildren();const el=document.createElement('span');el.className='state'+(error?' error':'');el.textContent=text;list.append(el);}
 function render(){list.replaceChildren();if(!items.length){state('Nenhum áudio cadastrado');return;}for(const item of items){const button=document.createElement('button');button.className='audio';button.type='button';button.title=`Enviar “${item.name}” na conversa atual`;const icon=document.createElement('span');icon.className='play';icon.textContent='▶';const name=document.createElement('span');name.textContent=(item.favorite?'★ ':'')+item.name;button.append(icon,name);button.onclick=()=>send(item,button);list.append(button);}}
 async function load(force=false){if(loading||(!force&&Date.now()-lastLoad<30000))return;loading=true;refresh.disabled=true;try{const data=await api('/library');items=data.items.filter(item=>(item.kind||'voice')==='voice').sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite)||a.name.localeCompare(b.name,'pt-BR'));lastLoad=Date.now();render();}catch(error){state(error.message,true);}finally{loading=false;refresh.disabled=false;}}
 function peerKey(){try{const url=new URL(location.href),hash=decodeURIComponent(url.hash.slice(1));if(url.origin!=='https://web.telegram.org'||!/^\/(a|k)\/?$/.test(url.pathname))return null;return /^(?:[1-9]\d{0,19}|@[A-Za-z0-9_]{5,32})$/.test(hash)?hash:null;}catch{return null;}}
 async function send(item,button){if(sending)return;const key=peerKey();if(!key){state('Abra uma conversa privada para enviar',true);setTimeout(render,2500);return;}sending=true;button.disabled=true;const original=button.textContent;button.textContent='Enviando…';try{const {target}=await api('/context',{method:'POST',body:{peerKey:key}});await api('/jobs',{method:'POST',body:{requestId:crypto.randomUUID(),dialogId:target.id,peerKey:key,steps:[{id:item.id,delay:0}],label:item.name}});button.textContent='Enviado ✓';setTimeout(()=>{button.disabled=false;render();},1800);}catch(error){button.textContent=error.message;setTimeout(()=>{button.textContent=original;button.disabled=false;},3000);}finally{sending=false;}}
 function composer(){return document.querySelector('#editable-message-text,[contenteditable="true"][data-placeholder*="essage" i],[contenteditable="true"][aria-label*="essage" i]');}
 function position(){const input=composer();if(!input){host.hidden=true;return;}let box=input.closest('.chat-input,.composer-wrapper,.input-message-container,[class*="composer"]')||input.parentElement;for(let i=0;i<3&&box?.parentElement;i++){const current=box.getBoundingClientRect(),parent=box.parentElement.getBoundingClientRect();if(parent.width>current.width&&parent.width<950&&parent.height<220)box=box.parentElement;else break;}const rect=box?.getBoundingClientRect();if(!rect||rect.width<220||rect.top<innerHeight*.45){host.hidden=true;return;}host.style.left=Math.max(8,rect.left)+'px';host.style.width=Math.min(rect.width,innerWidth-rect.left-8)+'px';host.style.bottom=Math.max(8,innerHeight-rect.top+7)+'px';host.hidden=false;load();}
 refresh.onclick=()=>{lastLoad=0;state('Atualizando…');load(true);};document.documentElement.append(host);new MutationObserver(position).observe(document.body,{childList:true,subtree:true});addEventListener('resize',position);addEventListener('hashchange',()=>{position();load();});setInterval(position,1500);position();
})();
